version: '3'

services:
  php8.2:
    container_name: 'php-8.2'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal remote_port=9003 remote_enable=1
    volumes:
      - ./app:/var/www/html
      - ./config/php.ini:/usr/local/etc/php/php.ini
    working_dir: /var/www/html


  php7.4:
    container_name: 'php-7.4'
    build:
      context: .
      dockerfile: Dockerfile2
    ports:
      - "8001:80"
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal remote_port=9003 remote_enable=1
    volumes:
      - ./app:/var/www/html
      - ./config/php.ini:/usr/local/etc/php/php.ini
    working_dir: /var/www/html


  composer:
    container_name: 'mycomposer'
    image: composer:2
    volumes:
      - ./app:/var/www/html
    working_dir: /var/www/html
    tty: true
    command: '/bin/bash'


  mariadb:
    container_name: 'mariadb'
    image: mariadb:latest
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dwcs
      MYSQL_USER: test
      MYSQL_PASSWORD: test
